In [302]:
# import package
import numpy as np
import pandas as pd


In [303]:
# load data and set 總成績 as prediction
# input 10 channel, output 1 channel

df = pd.read_csv('Data.csv')
train_sol = np.array(df['總成績']).T
df = df.drop('總成績', axis=1)
train_in = np.array(df)   


In [304]:
# initialize nn_weights

np.random.seed(1)

nn_weights =(2 * np.random.random((10,1)) - 1) / 100

loss = []

# train the network

for i in range(100):

    # Calculate the outputs for each training examples
    train_out = 1 / (1 + np.exp(-(np.dot(train_in, nn_weights)))) * 1000

    aloss = ((train_sol - train_out.T)**2).mean()
    print(aloss)
    loss.append(aloss)
   
    # Run the NN adjustments 
    nn_weights = nn_weights + np.dot(train_in.T, np.multiply(np.multiply((train_sol - train_out.T), train_out.T).T, (1 - train_out))) 

print("loss=", loss)  
print("nn_weight=")
print(nn_weights)




17935.790998707114
[[ 34.968007  ]
 [ 50.15063357]
 [ 77.53059174]
 [ 52.27169517]
 [ 34.44719576]
 [ 33.64211553]
 [ 78.20557478]
 [ 88.91379688]
 [ 63.5688225 ]
 [ 41.26703834]
 [ 94.55407371]
 [ 87.96075264]
 [449.24340535]
 [320.72665377]]
847393.5714285715
[[1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]]
847393.5714285715
[[1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]]
847393.5714285715
[[1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]]
847393.5714285715
[[1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]]
847393.5714285715
[[1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]
 [1000.]]
847393.5714285715
[[1000.]
 [10

In [305]:
# test

test_in = [11,64,9,0,0,18.25,85,48,71,68]

print(np.dot(test_in, nn_weights))

[3.79960679e+16]
